### ISSUE TITLE
No warnings "modification of a read-only value attempted" when updating a constant in eval block

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#269]
env: perl 5.22.0 
````
> perl -e 'use constant roref => \2; eval { for (roref) { $_ = 42 } }; print $@'
Modification of a read-only value attempted at -e line 1.
> perlcc -r -e 'use constant roref => \2; eval { for (roref) { $_ = 42 } }; print $@'
````

**Comment by atoomic** [comment]
close 307 as a duplicate

**Comment by atoomic** [comment]
testc.sh 269

**Comment by toddr** [comment]
Given this would only be an issue if we attempt to write to a constant in pure perl code, we're assuming this isn't a major issue for now.

**Comment by rurban** [comment]
The lhs in the assign is somehow corrupt. 
```
Program received signal SIGSEGV, Segmentation fault.
0x00000001002298fe in Perl_sv_setsv_flags (dstr=0x10046d870 <sv_list+112>,
    sstr=0x10046d8a8 <sv_list+168>, flags=1538) at sv.c:4339
4339		    SvIV_set(dstr,  SvIVX(sstr));
(gdb) bt
#0  0x00000001002298fe in Perl_sv_setsv_flags (dstr=0x10046d870 <sv_list+112>,
    sstr=0x10046d8a8 <sv_list+168>, flags=1538) at sv.c:4339
#1  0x00000001001df6bc in Perl_pp_sassign () at pp_hot.c:231
#2  0x0000000100185c1c in Perl_runops_debug () at dump.c:2234
#3  0x0000000100077857 in S_run_body (oldscope=1) at perl.c:2448
#4  0x0000000100076bd8 in perl_run (my_perl=0x100604bd0) at perl.c:2371
#5  0x0000000100004c3b in main ()
(gdb) p *dstr
$1 = {sv_any = 0x0, sv_refcnt = 3, sv_flags = 4353, sv_u = {svu_pv = 0x0, svu_iv = 0, svu_uv = 0,
    svu_nv = 0, svu_rv = 0x0, svu_rx = 0x0, svu_array = 0x0, svu_hash = 0x0, svu_gp = 0x0,
    svu_fp = 0x0}, sv_debug_optype = 0, sv_debug_inpad = 0, sv_debug_line = 0, sv_debug_serial = 0,
  sv_debug_file = 0x0, sv_debug_parent = 0x0}
(gdb) sd dstr
$2 = {sv_any = 0x0, sv_refcnt = 3, sv_flags = 4353, sv_u = {svu_pv = 0x0, svu_iv = 0, svu_uv = 0,
    svu_nv = 0, svu_rv = 0x0, svu_rx = 0x0, svu_array = 0x0, svu_hash = 0x0, svu_gp = 0x0,
    svu_fp = 0x0}, sv_debug_optype = 0, sv_debug_inpad = 0, sv_debug_line = 0, sv_debug_serial = 0,
  sv_debug_file = 0x0, sv_debug_parent = 0x0}
ALLOCATED at (unknown):0 by (none) (parent 0x0); serial 0
SV = IV(0x0) at 0x10046d870
  REFCNT = 3
  FLAGS = (IOK,pIOK)

Program received signal SIGSEGV, Segmentation fault.
```
