### ISSUE TITLE
-fno-cow SEGV

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#362]
SEGV only with 5.22.1 not-debugging on some systems.
when using a m//mig regexp. @atoomic is investigating

**Comment by atoomic** [comment]
can reproduce the segfault with perl5.22.1 and this program

```perl
#!./perl

sub like ($$@)   { like_yn( 0, @_ ) };
sub unlike ($$@) { like_yn( 1, @_ ) };    # no segfault if commented

sub like_yn {
    return re::is_regexp(123); # no segfault if commented
}

sub run_multiple_progs {
    my $results = q{};
    $results =~ s/^(syntax|parse) error/syntax error/mig; # no segfault if commented
}

{
    eval 'use Scalar::Util "dualvar";'; # no segfault if commented
}

print "ok\n";
```

```
> rm -f test; perlcc -O1 test.pl; ./test
ok

> rm -f test; perlcc -O2 test.pl; ./test
Segmentation fault
```

gdb 
```
Program received signal SIGSEGV, Segmentation fault.
0x003a3c8d in _int_realloc (av=0x4c23a0, oldp=0x812bb00, oldsize=88, nb=120) at malloc.c:5332
5332		unlink(av, next, bck, fwd);
```

**Comment by atoomic** [comment]
```diff
diff --git a/lib/B/C.pm b/lib/B/C.pm
index 617d88d..361f0ea 100644
--- a/lib/B/C.pm
+++ b/lib/B/C.pm

 sub IsCOW {
-    return ( $_[0]->FLAGS & SVf_IsCOW );    # since 5.22
+    return ( $_[0]->FLAGS & SVf_IsCOW ) && $B::C::cow;    # since 5.22
 }

```

**Comment by atoomic** [comment]
the previous patch fix a few segfault but here is another one easier to reproduce

```perl
#!./perl

package Foo::Bar {
    sub new {  }
}
my $sub = "new";
Foo::Bar->$sub;

print qq{ok\n};
```

```
> rm -f test; perlcc -O1 test.t; ./test
ok
> rm -f test; perlcc -O2 test.t; ./test
Segmentation fault

 > rm -f ./a.out; perlcc -O1 -e 'package Foo::Bar { sub new {}} my $sub = "new"; Foo::Bar->$sub; print qq{ok\n};'; ./a.out
ok
> rm -f ./a.out; perlcc -O2 -e 'package Foo::Bar { sub new {}} my $sub = "new"; Foo::Bar->$sub; print qq{ok\n};'; ./a.out
Segmentation fault
```

gdb
```
Program received signal SIGSEGV, Segmentation fault.
0x0017bcfa in Perl_gv_fetchmethod_pvn_flags ()
   from /usr/local/cpanel/3rdparty/perl/522/lib/perl5/5.22.1/i386-linux-64int/CORE/libperl.so
```

**Comment by atoomic** [comment]
additional problem discovered when compiling re/reg_mesg.t with HEAD @dc166ff110

```
reg_mesg.bin: regcomp.c:9113: S_get_invlist_iter_addr: Assertion `((svtype)((invlist)->sv_flags & 0xff)) == SVt_INVLIST' failed.

Program received signal SIGABRT, Aborted.
0x00130416 in __kernel_vsyscall ()
(gdb) bt
#0  0x00130416 in __kernel_vsyscall ()
#1  0x0063c871 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0x0063e14a in abort () at abort.c:92
#3  0x00635b8b in __assert_fail_base (fmt=0x76ae98 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x4dc05c "((svtype)((invlist)->sv_flags & 0xff)) == SVt_INVLIST", file=0x4dc85c "regcomp.c",
    line=9113, function=0x4e4dbf "S_get_invlist_iter_addr") at assert.c:96
#4  0x00635c46 in __assert_fail (assertion=0x4dc05c "((svtype)((invlist)->sv_flags & 0xff)) == SVt_INVLIST",
    file=0x4dc85c "regcomp.c", line=9113, function=0x4e4dbf "S_get_invlist_iter_addr") at assert.c:105
#5  0x0024de88 in S_get_invlist_iter_addr (invlist=0x5788d8) at regcomp.c:9113
#6  0x0024dee3 in S_invlist_iterinit (invlist=0x5788d8) at regcomp.c:9123
#7  0x0026770f in S_handle_regex_sets (pRExC_state=0xbfffe91c, return_invlist=0x0, flagp=0xbfffdb28, depth=5,
    oregcomp_parse=0x82bb029 "?[ ( ) ])") at regcomp.c:13933
#8  0x00256d16 in S_reg (pRExC_state=0xbfffe91c, paren=91, flagp=0xbfffdb28, depth=5) at regcomp.c:10428
#9  0x0025e17e in S_regatom (pRExC_state=0xbfffe91c, flagp=0xbfffddc0, depth=4) at regcomp.c:11725
#10 0x00259a81 in S_regpiece (pRExC_state=0xbfffe91c, flagp=0xbfffde60, depth=3) at regcomp.c:10809
#11 0x00259437 in S_regbranch (pRExC_state=0xbfffe91c, flagp=0xbfffe4ac, first=1, depth=2) at regcomp.c:10734
#12 0x002572b6 in S_reg (pRExC_state=0xbfffe91c, paren=0, flagp=0xbfffe7f4, depth=1) at regcomp.c:10484
#13 0x0024526a in Perl_re_op_compile (patternp=0x0, pat_count=1, expr=0x82be844, eng=0x5751a0, old_re=0x0,
    is_bare_re=0x0, orig_rx_flags=0, pm_flags=0) at regcomp.c:6881
#14 0x0016ebdf in Perl_pmruntime (o=0x82be864, expr=0x82be844, repl=0x0, isreg=true, floor=0) at op.c:5581
#15 0x00217804 in Perl_yyparse (gramtype=258) at perly.y:1038
#16 0x003aa0b8 in S_doeval (gimme=1, outside=0x82b9a9c, seq=8281, hh=0x82b9ba0) at pp_ctl.c:3491
#17 0x003b1fd0 in Perl_pp_entereval () at pp_ctl.c:4302
#18 0x0028f5bb in Perl_runops_debug () at dump.c:2234
#19 0x0019fd34 in S_run_body (oldscope=1) at perl.c:2443
#20 0x0019f325 in perl_run (my_perl=0x81ff008) at perl.c:2371
#21 0x081387ce in main ()
```

**Comment by rurban** [comment]
Fix with the rearranged -fcow implementation
