### ISSUE TITLE
fork causes infinite recursion on windows-mingw

### ISSUE THREAD

**Issue by constantined** [rurban/perl-compiler#419]
Testcase:
```perl
my $pid = fork;
warn "$$ $pid";
```
Stack trace:
```
#0  0x0000000000c12679 in Perl_ptr_table_fetch (my_perl=0x403a2e58,
    tbl=0x403b2360, sv=0x1324ce8 <padname_8_list+37128>) at ..\sv.c:13745
#1  0x0000000000dc862e in Perl_padname_dup (my_perl=0x403a2e58,
    src=0x1324ce8 <padname_8_list+37128>, param=0x3e2af760) at ..\pad.c:2940
#2  0x0000000000dc86ba in Perl_padname_dup (my_perl=0x403a2e58,
    src=0x1324ce8 <padname_8_list+37128>, param=0x3e2af760) at ..\pad.c:2952
#3  0x0000000000dc86ba in Perl_padname_dup (my_perl=0x403a2e58,
    src=0x1324ce8 <padname_8_list+37128>, param=0x3e2af760) at ..\pad.c:2952
...
```
Temporary workaround:
```patch
--- a/pad.c
+++ b/pad.c
@@ -2947,7 +2947,7 @@ Perl_padname_dup(pTHX_ PADNAME *src, CLONE_PARAMS *param)
        return dst;
     }

-    dst = PadnameOUTER(src)
+    dst = FALSE  //PadnameOUTER(src)
      ? newPADNAMEouter(padname_dup(PADNAME_FROM_PV(PadnamePV(src)), param))
         : newPADNAMEpvn_flags(PadnamePV(src), PadnameLEN(src), PadnameUTF8(src));
     ptr_table_store(PL_ptr_table, src, dst);
```

**Comment by rurban** [comment]
OUTER is wrong? Ouch. I hope there are better fixes for this.

**Comment by rurban** [comment]
Yes, I know. I'm the one who is setting this OUTER and the static padname struct. I have to avoid the recursion problem somehow. Probably only broken with threads.
